### ISSUE TITLE
Phase 0: Prototyping

### ISSUE THREAD

**Issue by nghia-nd** [vinmakersoc/vinuniverse_campus_app#2]
# Deliverables
A basic application with UI and weblink to VinUni website and information

# Design file
[Figma](https://www.figma.com/file/mZt5s0OWKeMgemBFA7MzmT/VinUniverse-copy?node-id=27%3A113) for reference

# Task
- [ ] UI Homepage as in Figma @nghia-nd 
  - On the homepage, create UI for many buttons to link to different webpage
- [ ] Implement basic weblink @tranhuonglantk 
  - Create a widget to open the given URL right in the application by clicking a button
- [ ] Floating button for contacts @hungnguyenhsgs 
  - Refer to the Figma design file. Implement a floating contact button, can display the contact (possibly using Dialog?), which then redirect the user to the Phone app directly if prompted.
